### ISSUE TITLE
Jib project hard dependency on Docker.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#105]
On my machine I use Podman instead of Docker.
When I use Maven to execute the package goal I see an exception thrown by JibProcessor.

```
[INFO] Horreum Backend .................................... FAILURE [ 42.961 s]
[INFO] Horreum Client ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  48.359 s
[INFO] Finished at: 2021-12-23T17:36:18Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.3.0.Final:build (default) on project horreum-backend: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.container.image.jib.deployment.JibProcessor#buildFromJar threw an exception: java.lang.RuntimeException: Unable to create container image
[ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:195)
[ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.buildFromJar(JibProcessor.java:135)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Cannot run program "docker": error=2, No such file or directory
[ERROR] 	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566)
[ERROR] 	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
[ERROR] 	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:88)
[ERROR] 	at com.google.cloud.tools.jib.builder.steps.StepsRunner.run(StepsRunner.java:219)
[ERROR] 	at com.google.cloud.tools.jib.api.Containerizer.run(Containerizer.java:366)
[ERROR] 	at com.google.cloud.tools.jib.api.JibContainerBuilder.containerize(JibContainerBuilder.java:598)
[ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:188)
[ERROR] 	... 12 more
[ERROR] Caused by: java.io.IOException: Cannot run program "docker": error=2, No such file or directory
[ERROR] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
[ERROR] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
[ERROR] 	at com.google.cloud.tools.jib.docker.DockerClient.docker(DockerClient.java:277)
[ERROR] 	at com.google.cloud.tools.jib.docker.DockerClient.load(DockerClient.java:193)
[ERROR] 	at com.google.cloud.tools.jib.builder.steps.LoadDockerStep.call(LoadDockerStep.java:74)
[ERROR] 	at com.google.cloud.tools.jib.builder.steps.StepsRunner.lambda$loadDocker$18(StepsRunner.java:618)
[ERROR] 	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
[ERROR] 	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
[ERROR] 	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
[ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] Caused by: java.io.IOException: error=2, No such file or directory
[ERROR] 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
[ERROR] 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
[ERROR] 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
[ERROR] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
[ERROR] 	... 11 more
[ERROR] -> [Help 1]
...
$ mvn -version
Apache Maven 3.8.3

openjdk version "11.0.11"
```

 Any known workarounds to allow the build to progress ?

**Comment by rvansa** [comment]
I thought that Podman installs a symlink from `docker` to `podman` - don't you have this?

**Comment by whitingjr** [comment]
No symlink in my distribution. An alias did exist but that wasn't getting picked up.
 After manually adding a symlink the build is working as expected. I'll close this issue.

**Comment by rvansa** [comment]
Maybe it's not installed by default with `podman`. `sudo dnf install -y podman-docker` could help.
