### ISSUE TITLE
`jakarta.persistence.NoResultException` is thrown if no run is found

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#1059]
```
2024-01-04 14:40:48,358 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1767) HTTP Request to /api/run/129257/summary failed, error id: a2a60ffb-c889-4703-b5f2-06d7086df125-172: jakarta.persistence.NoResultException: No result found for query [SELECT run.id, run.start, run.stop, run.testid, run.owner, run.access, run.token, run.trashed, run.description, run.metadata IS NOT NULL as has_metadata, (SELECT name FROM test WHERE test.id = run.testid) as testname, (SELECT COALESCE(jsonb_agg(jsonb_build_object('id', schema.id, 'uri', rs.uri, 'name', schema.name, 'source', rs.source, 'type', rs.type, 'key', rs.key, 'hasJsonSchema', schema.schema IS NOT NULL)), '[]') FROM run_schemas rs JOIN schema ON schema.id = rs.schemaid WHERE rs.runid = run.id) as schemas, (SELECT json_agg(id ORDER BY id) FROM dataset WHERE runid = run.id) as datasets, (SELECT jsonb_agg(jsonb_build_object('schemaId', schema_id, 'error', error)) AS errors FROM run_validationerrors WHERE run_id = ? GROUP BY run_id) AS validationErrors FROM run where id = ?]
	at org.hibernate.query.spi.AbstractSelectionQuery.getSingleResult(AbstractSelectionQuery.java:476)
	at io.hyperfoil.tools.horreum.svc.RunServiceImpl.getRunSummary(RunServiceImpl.java:243)
	at io.hyperfoil.tools.horreum.svc.RunServiceImpl_Subclass.getRunSummary$$superforward(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.RunServiceImpl_Subclass$$function$$5.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.hyperfoil.tools.horreum.server.RolesInterceptor.intercept(RolesInterceptor.java:53)
	at io.hyperfoil.tools.horreum.server.RolesInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at io.hyperfoil.tools.horreum.svc.RunServiceImpl_Subclass.getRunSummary(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.RunServiceImpl_ClientProxy.getRunSummary(Unknown Source)
	at io.hyperfoil.tools.horreum.api.services.RunService$quarkusrestinvoker$getRunSummary_29107bb2e6315fb3d9865df0d05659ec8a419bba.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by johnaohara** [comment]
I have removed the 0.11 milestone, we have a work around for this and can fix this in a point release after 0.11 has been released
