### ISSUE TITLE
Sample Test not loading. 404 Not found.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#1161]
**Describe the bug**

Since commit [bfbb360](https://github.com/Hyperfoil/Horreum/commit/bfbb3608a23f5d831c57b25c6378ab3879be6270) on master the ability to load a Test is failing.

```
2024-01-24 11:12:10,446 DEBUG [org.jbo.res.rea.ser.han.ParameterHandler] (executor-thread-1) Error occurred during parameter extraction: jakarta.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handleResult(ParameterHandler.java:113)
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handle(ParameterHandler.java:59)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:137)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NumberFormatException: For input string: "NaN"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.valueOf(Integer.java:999)
	at io.quarkus.generated.int$quarkusrestparamConverter$.convert(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handleResult(ParameterHandler.java:108)
	... 10 more

```

Feel free to attach screenshots as well.

![test11-404](https://github.com/Hyperfoil/Horreum/assets/708428/ec51ca30-8047-49ca-bfb0-3df994653070)

**To Reproduce**

start quarkus:dev -pl 'horreum-backend'
run the script to create dummy data for development work `infra-legacy/example-configuration.sh`
login using dummy user account
choose the test named "Roadrunner Test"

Any sample data would help greatly.

`infra-legacy/example-configuration.sh`

**Version**

What is the version of Horreum ?

```
0.10.7
```

**Java**

What is the version of Java ?

```
17
```

**Browser**

Which is the version of your browser ?

replicated issue with FF and Chrome

**Comment by johnaohara** [comment]
@whitingjr are you sure that commit is the issue? https://github.com/Hyperfoil/Horreum/commit/bfbb3608a23f5d831c57b25c6378ab3879be6270 has been reverted: https://github.com/Hyperfoil/Horreum/commit/8f0d1a280e705f4ee2ee20d1de44dc10f0300e8b

**Comment by johnaohara** [comment]
I have just built from : https://github.com/Hyperfoil/Horreum/commit/6184266a5dcad57d3f08141bf53e7f40611bf551

I see the following loading the example data

```
$ ./infra-legacy/example-configuration.sh 
POST /schema
POST /config/backends
POST /test
POST /schema
POST /schema
POST /schema/2/transformers
POST /test
POST /test/11/transformers
POST /run/test?test=11
POST /schema/3/labels
POST /schema/3/labels
POST /alerting/variables?test=11
POST /subscriptions/11
POST /notifications/settings?name=user&team=false
POST /action/allowedSites
POST /action
POST /action
########################
#   IMPORT SUCEEEDED   #
########################
```

**Comment by whitingjr** [comment]
Just pulled and tested the latest commit 6184266a5dcad57d3f08141bf53e7f40611bf551 as of today and this is no longer an issue.
