### ISSUE TITLE
NPE calling io.quarkus.security.identity.SecurityIdentity.getRoles()

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#1445]
**Describe the bug**

When the config option `horreum.roles.provider=keycloak` is set, the following exception is thrown when a user attempts to log in:

```
2024-03-07 12:21:40,653 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-2) HTTP Request to /api/user/roles failed, error id: 658e1b00-c98d-4618-b168-d316ddaab9e1-3: java.lang.NullPointerException: Cannot invoke "io.quarkus.security.identity.SecurityIdentity.getRoles()" because "this.identity" is null
	at io.hyperfoil.tools.horreum.svc.UserServiceImpl.getRoles(UserServiceImpl.java:69)
	at io.hyperfoil.tools.horreum.api.internal.services.UserService$quarkusrestinvoker$getRoles_34a90be96945d58693e1819e1692bb3a3951fdd3.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by johnaohara** [comment]
If I completely remove `DatabaseUserServiceImpl` from the project , the injected `SecurityIdentity` in `UserServiceImpl` is no longer null

With both `UserServiceImpl` and `DatabaseUserServiceImpl` included the project, when Horreum starts up, the following warning is displayed:

```
2024-03-07 13:56:47,327 WARN  [io.qua.arc.impl] (Quarkus Main Thread) 
================================================================================
CDI: programmatic lookup problem detected
-----------------------------------------
At least one bean matched the required type and qualifiers but was marked as unused and removed during build

Stack frame: io.quarkus.arc.runtime.BeanContainerImpl.beanInstanceFactory(BeanContainerImpl.java:31)
Required type: class io.hyperfoil.tools.horreum.svc.UserServiceImpl
Required qualifiers: [@jakarta.enterprise.inject.Default()]
Removed beans:
	- CLASS bean  [types=[class io.hyperfoil.tools.horreum.svc.UserServiceImpl, interface io.hyperfoil.tools.horreum.api.internal.services.UserService], qualifiers=null]
Solutions:
	- Application developers can eliminate false positives via the @Unremovable annotation
	- Extensions can eliminate false positives via build items, e.g. using the UnremovableBeanBuildItem
	- See also https://quarkus.io/guides/cdi-reference#remove_unused_beans
	- Enable the DEBUG log level to see the full stack trace
================================================================================
```

**Comment by stalep** [comment]
Hm, I'm not sure that I like the sound of that... :)

**Comment by barreiro** [comment]
@johnaohara yeah, we need an `UserServiceProvider` to decide the implementation at runtime

**Comment by johnaohara** [comment]
There is another annotation that I think will work `@LookupIfProperty` removes need to create a `Provider` and instantiating beans programatically
