### ISSUE TITLE
Server log WARN : DateTimeParseException

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#1514]
**Describe the bug**

The following server WARN messages are being logged:

```
2024-03-19 08:12:33,735 WARN  [io.hyp.too.hor.svc.Util] (executor-thread-22) failed to convert  to timestamp using : java.time.format.DateTimeParseException: Text '' could not be parsed at index 0
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2052)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1954)
	at java.base/java.time.ZonedDateTime.parse(ZonedDateTime.java:600)
	at io.hyperfoil.tools.horreum.svc.Util.toInstant(Util.java:654)
	at io.hyperfoil.tools.horreum.svc.TestServiceImpl.listLabelValues(TestServiceImpl.java:574)
	at io.hyperfoil.tools.horreum.svc.TestServiceImpl_Subclass.listLabelValues$$superforward(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.TestServiceImpl_Subclass$$function$$10.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.hyperfoil.tools.horreum.server.RolesInterceptor.intercept(RolesInterceptor.java:53)
	at io.hyperfoil.tools.horreum.server.RolesInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at io.hyperfoil.tools.horreum.svc.TestServiceImpl_Subclass.listLabelValues(Unknown Source)
	at io.hyperfoil.tools.horreum.api.services.TestService$quarkusrestinvoker$listLabelValues_0a886b7b0505ea93c534bdfb2272905dab70d786.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by willr3** [comment]
```
 failed to convert  to timestamp using : 
```
This comes from https://github.com/Hyperfoil/Horreum/blob/master/horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java#L656
```
log.warn("failed to convert "+time+" to timestamp using "+str,e);
```
the `time` and `str` are empty so I supsect the attempted upload did not include a start or stop timstamp. I think this was invalid user input given the current Horreum requirements. Is the bug that we are logging the stack trace for what should be a normal gating of invalid input?

**Comment by willr3** [comment]
I see Horreum will already replace missing `start` and `stop` with the current timestamp. In that case I think Horreum should not warn when the user does not provide a `start` and `stop` and should only log the warning when a value was provided but horreum could not process it.
