### ISSUE TITLE
`ActionServiceTest.testSlackAction()` test fails intermittently 

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#1724]
**Describe the bug**

`ActionServiceTest.testSlackAction()` test fails intermittently with the exception below;

```
io.hyperfoil.tools.horreum.svc.ActionServiceTest.testSlackAction(TestInfo) -- Time elapsed: 1.097 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Test case ERRORCHANNEL failed ==> expected: <1> but was: <0>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:563)
	at io.hyperfoil.tools.horreum.svc.ActionServiceTest.testSlackAction(ActionServiceTest.java:149)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1013)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:827)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by johnaohara** [comment]
haha, i am forgetting what I have already opened!
