### ISSUE TITLE
Changes are not persisted due to `change_pkey` constraint violation

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#1852]
**Describe the bug**

Changes are occasionally not persisted, caused by a PK constraint violation on insert

```
2024-06-27 12:45:02,146 a50236a963af quarkus-run.jar[7] WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (executor-thread-12352) SQL Error: 0, SQLState: 23505
2024-06-27 12:45:02,147 a50236a963af quarkus-run.jar[7] ERROR [org.hib.eng.jdb.spi.SqlExceptionHelper] (executor-thread-12352) ERROR: duplicate key value violates unique constraint "change_pkey"
2024-06-27 12:45:02,148 a50236a963af quarkus-run.jar[7] WARN  [io.agr.pool] (executor-thread-12352) Datasource '<default>': JDBC resources leaked: 2 ResultSet(s) and 2 Statement(s)
2024-06-27 12:45:02,149 a50236a963af quarkus-run.jar[7] ERROR [io.hyp.too.hor.bus.TaskQueue] (executor-thread-12352) Error executing task in the queue for test 290: org.hibernate.exception.ConstraintViolationException: could not execute statement [ERROR: duplicate key value violates unique constraint "change_pkey"] [insert into change (confirmed,dataset_id,description,timestamp,variable_id,id) values (?,?,?,?,?,?)]
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:97)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:58)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
	at org.hibernate.engine.jdbc.mutation.internal.AbstractMutationExecutor.performNonBatchedMutation(Abst
...
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "change_pkey"
```

**Comment by lampajr** [comment]
Looks like that this issue is also preventing to upload new Runs for specific Tests, even if it does not seem deterministic:
```sh
2024-07-02 04:33:16,340 quarkus-run.jar[7] ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-198) HTTP Request to /api/run/data?start=%24.build-timestamp&stop=%24.build-timestamp&test=Quarkus+-+config-quickstart+-+JVM&owner=perf-team&access=PUBLIC&schema=urn%3Aquarkus-quickstart%3A0.1 failed, error id: e0d21440-f752-4364-a436-806a8514256c-18: org.hibernate.exception.GenericJDBCException: could not execute statement [ERROR: current transaction is aborted, commands ignored until end of transaction block] [insert into change (confirmed,dataset_id,description,timestamp,variable_id,id) values (?,?,?,?,?,?)]
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:63)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
...
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "change_pkey"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
```

**Comment by lampajr** [comment]
After further investigation looks like the issue was introduced by https://github.com/Hyperfoil/Horreum/commit/89d6d54cb8ef96109c17c8bbd593c851ec2c8f23#diff-45367418913b4890b11d993396ff3db5fae373f9f63183dfc0c243cf45557913R4092 and it is affecting Horreum instances that were running before that change was applied.

The new sequences have been generated starting from `1` even if there were records with higher ids (those that were generated with the old `hibernate_sequence`).

As part of this issue we might set which sequence we are using here https://github.com/Hyperfoil/Horreum/blob/master/horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/alerting/ChangeDAO.java#L29 (do the same for all other entities that are doing the same)
