### ISSUE TITLE
Unable to search for users to add to a team

### ISSUE THREAD

**Issue by willr3** [Hyperfoil/Horreum#1868]
**Describe the bug**

I am unable to search for existing users to add them to a team. Searching the `Available Users` results in an error message `Unable to search for users` and the server logs the following exception.
```
2024-07-07 00:57:45,145 WARN  [io.hyp.too.hor.svc.use.KeycloakUserBackend] (executor-thread-2103) Unable to list machine accounts for team ocp-perfscale-team: jakarta.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:242)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:216)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:59)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:136)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:103)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:102)
	at jdk.proxy2/jdk.proxy2.$Proxy121.getUserMembers(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.user.KeycloakUserBackend.machineAccounts(KeycloakUserBackend.java:368)
	at io.hyperfoil.tools.horreum.svc.user.KeycloakUserBackend_ClientProxy.machineAccounts(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.UserServiceImpl.safeMachineAccounts(UserServiceImpl.java:215)
	at io.hyperfoil.tools.horreum.svc.UserServiceImpl.teamMembers(UserServiceImpl.java:100)
	at io.hyperfoil.tools.horreum.svc.UserServiceImpl_Subclass.teamMembers$$superforward(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.UserServiceImpl_Subclass$$function$$10.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
	at io.quarkus.security.runtime.interceptor.SecurityHandler.handle(SecurityHandler.java:47)
	at io.quarkus.security.runtime.interceptor.AuthenticatedInterceptor.intercept(AuthenticatedInterceptor.java:29)
	at io.quarkus.security.runtime.interceptor.AuthenticatedInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor.intercept(StandardSecurityCheckInterceptor.java:44)
	at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor_AuthenticatedInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at io.hyperfoil.tools.horreum.svc.UserServiceImpl_Subclass.teamMembers(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.UserServiceImpl_ClientProxy.teamMembers(Unknown Source)
	at io.hyperfoil.tools.horreum.api.internal.services.UserService$quarkusrestinvoker$teamMembers_e20fd40d2042db5da7dfb0a2fb753740a5a1d15f.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:599)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

Feel free to attach screenshots as well.

**To Reproduce**

Steps to reproduce the behavior.

Any sample data would help greatly.

**Version**

What is the version of Horreum ?

If you are using a development branch; what is the commit id ?

```
git rev-parse HEAD
```

**Java**

What is the version of Java ?

```
java -version
```

**PostgreSQL**

What is the version of PostgreSQL ?

```
psql --version
```

**OS**

Which Operating System (OS) is used ?

**Browser**

Which is the version of your browser ?

**Tip**

Use \`\`\` before and after the text to keep the output as is.

**Comment by barreiro** [comment]
I'll have a look
