### ISSUE TITLE
KeycloakUserServiceTest occasionally failing

### ISSUE THREAD

**Issue by lampajr** [Hyperfoil/Horreum#2086]
**Describe the bug**

Test `KeycloakUserServiceTest` is occasionally failing with:

```bash
2024-10-15 13:35:57,816 WARN  [io.hyp.too.hor.svc.use.KeycloakUserBackend] (main) Could not add admin role to user some-random-dude due to User some-random-dude does not exist
Error:  Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 63.65 s <<< FAILURE! -- in io.hyperfoil.tools.horreum.svc.KeycloakUserServiceTest
Error:  io.hyperfoil.tools.horreum.svc.KeycloakUserServiceTest.apiKeys -- Time elapsed: 0.615 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Expected a notification of key about to expire ==> expected: <false> but was: <true>
	at io.hyperfoil.tools.horreum.svc.UserServiceAbstractTest.lambda$apiKeys$56(UserServiceAbstractTest.java:617)
	at io.hyperfoil.tools.horreum.svc.UserServiceAbstractTest.overrideTestSecurity(UserServiceAbstractTest.java:76)
	at io.hyperfoil.tools.horreum.svc.UserServiceAbstractTest.apiKeys(UserServiceAbstractTest.java:578)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:973)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:823)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**To Reproduce**

See job https://github.com/Hyperfoil/Horreum/actions/runs/11347129760/job/31557779361?pr=2085 as example

**Additional Context**

Re-running the CI makes the test green, thus I think it is actually a flaky test.

**Comment by stalep** [comment]
It fails locally as well:

`[ERROR] Tests run: 10, Failures: 0, Errors: 1, Skipped: 9, Time elapsed: 16.47 s <<< FAILURE! -- in io.hyperfoil.tools.horreum.svc.KeycloakUserServiceTest
[ERROR] io.hyperfoil.tools.horreum.svc.KeycloakUserServiceTest.teamTest -- Time elapsed: 0.001 s <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:611)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:695)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at io.quarkus.test.junit.TestResourceUtil$TestResourceManagerReflections.startReflectively(TestResourceUtil.java:214)
        at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:212)
        at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:578)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:628)
        ... 1 more
        Suppressed: java.lang.RuntimeException: Unable to stop Quarkus test resource io.hyperfoil.tools.horreum.test.HorreumKeycloakTestResourceLifecycleManager@a531c51
                at io.quarkus.test.common.TestResourceManager.close(TestResourceManager.java:241)
                at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:289)
                ... 3 more
        Caused by: java.lang.IllegalArgumentException: accessToken cannot be null
                at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
                at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
                at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
                at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
                at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
                at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
                at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
                at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
                at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
                at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
                at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
                at io.quarkus.test.keycloak.server.KeycloakTestResourceLifecycleManager.stop(KeycloakTestResourceLifecycleManager.java:175)
                at io.quarkus.test.common.TestResourceManager.close(TestResourceManager.java:239)
                ... 4 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.test.junit.TestResourceUtil$TestResourceManagerReflections.startReflectively(TestResourceUtil.java:211)
        ... 4 more
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class io.hyperfoil.tools.horreum.test.HorreumKeycloakTestResourceLifecycleManager
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource class io.hyperfoil.tools.horreum.test.HorreumKeycloakTestResourceLifecycleManager
        at io.quarkus.test.common.TestResourceManager$TestResourceRunnable.run(TestResourceManager.java:674)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        ... 3 more
Caused by: java.lang.IllegalArgumentException: accessToken cannot be null
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
        at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
        at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
        at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:240)
        at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
        at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
        at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
        at io.quarkus.test.keycloak.server.KeycloakTestResourceLifecycleManager.postRealm(KeycloakTestResourceLifecycleManager.java:54)
        at io.quarkus.test.keycloak.server.KeycloakTestResourceLifecycleManager.start(KeycloakTestResourceLifecycleManager.java:43)
        at io.hyperfoil.tools.horreum.test.HorreumKeycloakTestResourceLifecycleManager.start(HorreumKeycloakTestResourceLifecycleManager.java:32)
        at io.quarkus.test.common.TestResourceManager$TestResourceRunnable.run(TestResourceManager.java:668)
        ... 4 more

`
