### ISSUE TITLE
Missing DB sequence `userinfo_apikey_id_seq`

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#2125]
**Describe the bug**

Starting Horreum from current master branch, with a production backup, results in the following error starting in Dev Mode:

```
2024-10-24 11:12:40,598 WARN  [io.agr.pool] (Quarkus Main Thread) Datasource 'migration': JDBC resources leaked: 15 ResultSet(s) and 0 Statement(s)
2024-10-24 11:12:41,889 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:116)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: jakarta.persistence.PersistenceException: [PersistenceUnit: <default>] Unable to build Hibernate SessionFactory
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.persistenceException(FastBootEntityManagerFactoryBuilder.java:129)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:89)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:73)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:154)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:61)
	... 1 more
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing sequence [userinfo_apikey_id_seq]
	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateSequence(AbstractSchemaValidator.java:186)
	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.performValidation(AbstractSchemaValidator.java:115)
	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.doValidation(AbstractSchemaValidator.java:77)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:289)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.lambda$process$5(SchemaManagementToolCoordinator.java:144)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:141)
	at io.quarkus.hibernate.orm.runtime.observers.SessionFactoryObserverForSchemaExport.sessionFactoryCreated(SessionFactoryObserverForSchemaExport.java:21)
	at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:323)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:87)
```

**Comment by lampajr** [comment]
Hey @johnaohara , I tried starting Horreum with a prod backup and I did not experience the same issue 🫤 

```bash
docker exec -u postgres <container-id> psql -U <user> -d <db> -c "SELECT sequence_schema, sequence_name
FROM information_schema.sequences WHERE sequence_name = 'userinfo_apikey_id_seq' 
ORDER BY sequence_name"

 sequence_schema |     sequence_name      
-----------------+------------------------
 public          | userinfo_apikey_id_seq
```

I tried with backup from `20241020060001`.

**Comment by johnaohara** [comment]
@lampajr thanks for checking, I may have an old backup, will double-check with a more recent backup

**Comment by lampajr** [comment]
> @lampajr thanks for checking, I may have an old backup, will double-check with a more recent backup

Worth to note that the sequence has been added in the latest changeset https://github.com/Hyperfoil/Horreum/blob/3ab8fed242f0e634b3dfb26d43dd7bf57462e8f8/horreum-backend/src/main/resources/db/changeLog.xml#L4571

So, when starting up the Horreum with the prod backup double check the changeset gets executed (as it is just in master atm)

**Comment by johnaohara** [comment]
I have re-tried to boot with a prod backup, I had set the incorrect prod user in `./horreum-backend/src/main/resources/db/changeLog.xml`

The sequence was craeted, but it was created by the wrong user
