### ISSUE TITLE
Quinoa build process fails due to openssl v3 library unsupported by react-scripts.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#226]
Using Fedora36 the platform packages are not able to build Horreum.
```
$ node --version
v16.14.0
$ npm --version
8.3.1
$ openssl version
OpenSSL 3.0.3 3 May 2022 (Library: OpenSSL 3.0.3 3 May 2022)
```
this is the error
```
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager] > node@0.1.0 build
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager] > react-scripts build --output-hashing=all --prod --aot --configuration=production --openssl-legacy-provider
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager] Creating an optimized production build...
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager] Error: error:0308010C:digital envelope routines::unsupported
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at new Hash (node:internal/crypto/hash:67:19)
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at Object.createHash (node:crypto:130:10)
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at module.exports (/home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/webpack/lib/util/createHash.js:135:53)
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at NormalModule._initBuildHash (/home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/webpack/lib/NormalModule.js:417:16)
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at handleParseError (/home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/webpack/lib/NormalModule.js:471:10)
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at /home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/webpack/lib/NormalModule.js:503:5
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at /home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/webpack/lib/NormalModule.js:358:12
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at /home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/loader-runner/lib/LoaderRunner.js:373:3
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at iterateNormalLoaders (/home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at iterateNormalLoaders (/home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at /home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/loader-runner/lib/LoaderRunner.js:236:3
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at runSyncOrAsync (/home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at iterateNormalLoaders (/home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at Array.<anonymous> (/home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at Storage.finished (/home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at /home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager] /home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/react-scripts/scripts/build.js:19
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]   throw err;
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]   ^
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager] Error: error:0308010C:digital envelope routines::unsupported
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at new Hash (node:internal/crypto/hash:67:19)
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at Object.createHash (node:crypto:130:10)
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at module.exports (/home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/webpack/lib/util/createHash.js:135:53)
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at NormalModule._initBuildHash (/home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/webpack/lib/NormalModule.js:417:16)
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at /home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/webpack/lib/NormalModule.js:452:10
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at /home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/webpack/lib/NormalModule.js:323:13
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at /home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/loader-runner/lib/LoaderRunner.js:367:11
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at /home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/loader-runner/lib/LoaderRunner.js:233:18
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at context.callback (/home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]     at /home/whitingjr/thebounty/work/redhat/java/Horreum/worktree/add-servlet-spec-tests-issue-#182/webapp/node_modules/babel-loader/lib/index.js:59:103 {
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]   library: 'digital envelope routines',
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]   reason: 'unsupported',
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[INFO] [io.quarkiverse.quinoa.deployment.PackageManager] }

```
  Configuring the [package.json](https://github.com/whitingjr/Horreum/commit/0a307ff460cb156836f9dc4556be1987a9a37621) file to use the [workaround](https://itsmycode.com/error-digital-envelope-routines-unsupported/) does not solve this issue.

**Comment by whitingjr** [comment]
this will be fixed when the [PR to backport](https://github.com/nodejs/node/pull/42972) is merged into nodejs/node/main.

**Comment by whitingjr** [comment]
a workaround has been [mentioned](https://github.com/nodejs/node/issues/43723#issuecomment-1191321224). The build completes > BUILD SUCCESS
