### ISSUE TITLE
DataSet$EventNew.toString() throws NPE if EventNew.DataSet is null

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#284]
Under error conditions, DataSet$EventNew.toString()  throws a NPE

```
2022-10-26 10:20:52,017 ERROR [io.hyp.too.hor.bus.TaskQueue] (executor-thread-959) Error executing task in the queue for test -1: java.lang.NullPointerException
        at io.hyperfoil.tools.horreum.entity.json.DataSet$EventNew.toString(DataSet.java:124)
        at java.base/java.util.Formatter$FormatSpecifier.printString(Formatter.java:3031)
        at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:2908)
        at java.base/java.util.Formatter.format(Formatter.java:2673)
        at java.base/java.util.Formatter.format(Formatter.java:2609)
        at java.base/java.lang.String.format(String.java:2897)
        at io.hyperfoil.tools.horreum.server.ErrorReporter.reportException(ErrorReporter.java:35)
        at io.hyperfoil.tools.horreum.server.ErrorReporter_ClientProxy.reportException(Unknown Source)
        at io.hyperfoil.tools.horreum.bus.MessageBus.lambda$subscribe$3(MessageBus.java:172)
        at io.hyperfoil.tools.horreum.bus.TaskQueue.executeOrAdd(TaskQueue.java:27)
        at io.hyperfoil.tools.horreum.bus.MessageBus.lambda$executeForTest$8(MessageBus.java:272)
        at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
        at io.hyperfoil.tools.horreum.svc.Util.lambda$executeBlocking$1(Util.java:481)
        at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:557)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by rvansa** [comment]
Actually this NPE is thrown on the `run`; fixed in e14634028f8f05b2322e952a5abb19a6b1ac30ac
