### ISSUE TITLE
Upgrade Webpack

### ISSUE THREAD

**Issue by jesperpedersen** [Hyperfoil/Horreum#300]
Upgrade to the latest Webpack - that will support both OpenSSL 1.1.x and 3.x

**Comment by jesperpedersen** [comment]
We need a

```
module.exports = {
    output: {
        hashFunction: "sha256"
    }
};
```

configuration

**Comment by johnaohara** [comment]
Is this node webpack? I thought we depended on Quarkus Quinoa for bundling the GUI, are we not tied to whatever version is pulled in from Quinoa?

**Comment by jesperpedersen** [comment]
We need a webapp/ that support OpenSSL 1.1.x and 3 using SHA256 so we don't have to rely on the `--openssl-legacy-provider` "hack"

**Comment by jesperpedersen** [comment]
```
[io.qua.qui.dep.pac.PackageManager] (build-60) Error: error:0308010C:digital envelope routines::unsupported
[io.qua.qui.dep.pac.PackageManager] (build-60)     at new Hash (node:internal/crypto/hash:71:19)
[io.qua.qui.dep.pac.PackageManager] (build-60)     at Object.createHash (node:crypto:133:10)
[io.qua.qui.dep.pac.PackageManager] (build-60)     at module.exports (webapp/node_modules/webpack/lib/util/createHash.js:135:53)
[io.qua.qui.dep.pac.PackageManager] (build-60)     at NormalModule._initBuildHash (webapp/node_modules/webpack/lib/NormalModule.js:417:16)
[io.qua.qui.dep.pac.PackageManager] (build-60)     at webapp/node_modules/webpack/lib/NormalModule.js:452:10
[io.qua.qui.dep.pac.PackageManager] (build-60)     at webapp/node_modules/webpack/lib/NormalModule.js:323:13
[io.qua.qui.dep.pac.PackageManager] (build-60)     at webapp/node_modules/loader-runner/lib/LoaderRunner.js:367:11
[io.qua.qui.dep.pac.PackageManager] (build-60)     at webapp/node_modules/loader-runner/lib/LoaderRunner.js:233:18
[io.qua.qui.dep.pac.PackageManager] (build-60)     at context.callback (webapp/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
[io.qua.qui.dep.pac.PackageManager] (build-60)     at webapp/node_modules/babel-loader/lib/index.js:59:103 {
[io.qua.qui.dep.pac.PackageManager] (build-60)   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[io.qua.qui.dep.pac.PackageManager] (build-60)   library: 'digital envelope routines',
[io.qua.qui.dep.pac.PackageManager] (build-60)   reason: 'unsupported',
[io.qua.qui.dep.pac.PackageManager] (build-60)   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[io.qua.qui.dep.pac.PackageManager] (build-60) }
```

So, it is likely Webpack and calling libraries

**Comment by jesperpedersen** [comment]
This will require a complete upgrade of the stack, since `react-scripts` goes from `4.0.3` to `5.0.1`
