### ISSUE TITLE
Generated OpenAPI invalid schema

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#315]
If you download the current OpenAPI schema from Horreum (i.e. https://horreum.corp.redhat.com/q/openapi) errors are thrown when it is parsed & validated.

For example, passing the schema into https://apitools.dev/swagger-parser/online/ creates the following errors;

```
Swagger schema validation failed.
  #/paths/~1api~1run~1{id}/get/responses/default must have required property 'description'
  #/paths/~1api~1run~1{id}/get/responses/default must have required property '$ref'
  #/paths/~1api~1run~1{id}/get/responses/default must match exactly one schema in oneOf


Error: Swagger schema validation failed.
  #/paths/~1api~1run~1{id}/get/responses/default must have required property 'description'
  #/paths/~1api~1run~1{id}/get/responses/default must have required property '$ref'
  #/paths/~1api~1run~1{id}/get/responses/default must match exactly one schema in oneOf

    at o (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:95564)
    at https://apitools.dev/swagger-parser/online/js/bundle.min.js:29:45042

SyntaxError: Swagger schema validation failed.
  #/paths/~1api~1run~1{id}/get/responses/default must have required property 'description'
  #/paths/~1api~1run~1{id}/get/responses/default must have required property '$ref'
  #/paths/~1api~1run~1{id}/get/responses/default must match exactly one schema in oneOf

    at Function.o [as syntax] (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:95564)
    at validateSchema (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:6322)
    at SwaggerParser.validate (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:3391)
```

**Comment by rvansa** [comment]
Fixed in 2e8a9200ece8f444399a476385e53ae9fabcc4dc
