### ISSUE TITLE
HorreumClientTest

### ISSUE THREAD

**Issue by jesperpedersen** [Hyperfoil/Horreum#324]
```
03:21:16,647 INFO  [org.testcontainers.DockerClientFactory] (main): Checking the system...
03:21:16,649 INFO  [org.testcontainers.DockerClientFactory] (main): ✔︎ Docker server version should be at least 1.6.0
03:21:17,149 INFO  [org.testcontainers.containers.DockerComposeContainer] (main): Preemptively checking local images for 'docker.io/postgres:12', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
03:21:17,232 INFO  [org.testcontainers.containers.DockerComposeContainer] (main): Preemptively checking local images for 'docker.io/dwdraju/alpine-curl-jq:latest', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
03:21:17,232 INFO  [org.testcontainers.containers.DockerComposeContainer] (main): Preemptively checking local images for 'docker.io/grafana/grafana:latest', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.212 s <<< FAILURE! - in io.hyperfoil.tools.HorreumClientTest
[ERROR] io.hyperfoil.tools.HorreumClientTest  Time elapsed: 1.212 s  <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Local Docker Compose not found. Is docker-compose on the PATH?
	at org.testcontainers.containers.LocalDockerCompose.invoke(DockerComposeContainer.java:792)
	at org.testcontainers.containers.DockerComposeContainer.runWithCompose(DockerComposeContainer.java:337)
	at org.testcontainers.containers.DockerComposeContainer.createServices(DockerComposeContainer.java:258)
	at org.testcontainers.containers.DockerComposeContainer.start(DockerComposeContainer.java:189)
	at io.hyperfoil.tools.HorreumTestExtension.startContainers(HorreumTestExtension.java:187)
	at io.hyperfoil.tools.HorreumTestExtension.beforeSuite(HorreumTestExtension.java:208)
	at io.hyperfoil.tools.HorreumTestClientExtension.beforeSuite(HorreumTestClientExtension.java:32)
	at io.hyperfoil.tools.HorreumTestExtension.beforeAll(HorreumTestExtension.java:202)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:395)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
```

**Comment by jesperpedersen** [comment]
Happens with a `podman only environment

**Comment by jesperpedersen** [comment]
```
03:29:54,954 INFO  [io.hyperfoil.tools.HorreumTestExtension] (main): Starting Infra: true
03:29:55,040 WARN  [org.testcontainers.utility.TestcontainersConfiguration] (main): Attempted to read Testcontainers configuration file at file:/home/jpedersen/.testcontainers.properties but the file was not found. Exception message: FileNotFoundException: /home/jpedersen/.testcontainers.properties (No such file or directory)
03:29:55,043 INFO  [org.testcontainers.utility.ImageNameSubstitutor] (main): Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
03:29:55,111 INFO  [io.hyperfoil.tools.HorreumTestExtension] (main): Waiting for Horreum infrastructure to start
03:29:55,117 WARN  [org.testcontainers.utility.ResourceReaper] (main): 
********************************************************************************
Ryuk has been disabled. This can cause unexpected behavior in your environment.
********************************************************************************
03:29:55,118 INFO  [org.testcontainers.containers.DockerComposeContainer] (main): Preemptively checking local images for 'quay.io/keycloak/keycloak:18.0.0', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
03:29:55,545 INFO  [org.testcontainers.dockerclient.DockerClientProviderStrategy] (main): Found Docker environment with Environment variables, system properties and defaults. Resolved dockerHost=unix:///run/user/1000/podman/podman.sock
03:29:55,547 INFO  [org.testcontainers.DockerClientFactory] (main): Docker host IP address is localhost
03:29:55,655 INFO  [org.testcontainers.DockerClientFactory] (main): Connected to docker: 
  Server Version: 4.3.1
  API Version: 1.41
  Operating System: fedora
  Total Memory: 63698 MB
03:29:55,656 INFO  [org.testcontainers.DockerClientFactory] (main): Checking the system...
```

**Comment by stalep** [comment]
Not able to recreate in master
