### ISSUE TITLE
Horreum Version Information popup is not displaying correct information

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#341]
**Describe the bug**

The Version Information popup is not displaying information about Horreum Version or Git commit id in our managed service;

<img width="562" alt="Screenshot 2023-01-16 at 17 55 55" src="https://user-images.githubusercontent.com/959822/212740932-974d3361-6d01-4b6e-a90e-8898f285e7a3.png">

**Comment by johnaohara** [comment]
backend is throwing the following exception:

```
2023-01-26 10:38:18,719 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-12705) Request failed: java.util.NoSuchElementException: SRCFG00014: The config property horreum.build.commit is required but it could not be found in any config source
        at io.smallrye.config.SmallRyeConfig.convertValue(SmallRyeConfig.java:298)
        at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:242)
        at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:167)
        at io.hyperfoil.tools.horreum.api.ConfigService.getString(ConfigService.java:43)
        at io.hyperfoil.tools.horreum.api.ConfigService.version(ConfigService.java:36)
        at io.hyperfoil.tools.horreum.api.ConfigService_Subclass.version$$superforward1(Unknown Source)
        at io.hyperfoil.tools.horreum.api.ConfigService_Subclass$$function$$2.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.security.runtime.interceptor.SecurityHandler.handle(SecurityHandler.java:27)
        at io.quarkus.security.runtime.interceptor.PermitAllInterceptor.intercept(PermitAllInterceptor.java:23)
        at io.quarkus.security.runtime.interceptor.PermitAllInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
        at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor.intercept(StandardSecurityCheckInterceptor.java:43)
        at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor_PermitAllInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
        at io.hyperfoil.tools.horreum.api.ConfigService_Subclass.version(Unknown Source)
        at io.hyperfoil.tools.horreum.api.ConfigService_ClientProxy.version(Unknown Source)
        at io.hyperfoil.tools.horreum.api.ConfigService$quarkusrestinvoker$version_7af5154464227a6629b9863f9c8943d93b1f1f52.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by johnaohara** [comment]
The build properties are not being copied into the publish images on quay.io:

https://github.com/Hyperfoil/Horreum/blob/master/horreum-backend/pom.xml#L195

**Comment by jesperpedersen** [comment]
The build properties should be generated for both SNAPSHOT and release builds. Otherwise it will end up saying `0.7-SNAPSHOT` even for `0.7.1`.

Same basically goes for the commit id.
