### ISSUE TITLE
AlertingServiceTest: Assertion failure

### ISSUE THREAD

**Issue by jesperpedersen** [Hyperfoil/Horreum#379]
```
Error:  io.hyperfoil.tools.horreum.svc.AlertingServiceTest.testFingerprintFilter(TestInfo)  Time elapsed: 0.494 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <4.0> but was: <3.0>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:70)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:65)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:886)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceTest.assertValue(AlertingServiceTest.java:255)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceTest.testFingerprintFilter(AlertingServiceTest.java:324)
```

**Comment by whitingjr** [comment]
Can you still recreate this test failure in master branch ?
