### ISSUE TITLE
git commands failing with pre-commit hook errors

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#396]
**Describe the bug**

executing some git commands are failing with following error message;

```
$ git cherry-pick --continue 
.husky/pre-commit: line 6: node/node/node_modules/npm/bin/npm: Not a directory
husky - pre-commit hook exited with code 126 (error)
```

**Comment by johnaohara** [comment]
This looks like it is related to the change to use Quinoa to handle nodejs download: https://github.com/Hyperfoil/Horreum/commit/ac278b859cdfe5a7a45ea65ca972be257d025955

`mvn clean package` now fails for me with  ;

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.16.2.Final:build (default) on project horreum-backend: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkiverse.quinoa.deployment.QuinoaProcessor#prepareQuinoaDirectory threw an exception: java.lang.RuntimeException: Error while installing NodeJS
[ERROR]         at io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerInstall.install(PackageManagerInstall.java:52)
[ERROR]         at io.quarkiverse.quinoa.deployment.QuinoaProcessor.prepareQuinoaDirectory(QuinoaProcessor.java:96)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: com.github.eirslett.maven.plugins.frontend.lib.InstallationException: Could not extract the Node archive
[ERROR]         at com.github.eirslett.maven.plugins.frontend.lib.NodeInstaller.installNodeDefault(NodeInstaller.java:209)
[ERROR]         at com.github.eirslett.maven.plugins.frontend.lib.NodeInstaller.install(NodeInstaller.java:95)
[ERROR]         at io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerInstall.install(PackageManagerInstall.java:42)
[ERROR]         ... 12 more
[ERROR] Caused by: com.github.eirslett.maven.plugins.frontend.lib.ArchiveExtractionException: Could not extract archive: '/working/projects/redHat/Hyperfoil/Horreum/horreum-backend/../webapp/node/cache/node-v18.1.0-linux-x64.tar.gz'
[ERROR]         at com.github.eirslett.maven.plugins.frontend.lib.DefaultArchiveExtractor.extract(ArchiveExtractor.java:139)
[ERROR]         at com.github.eirslett.maven.plugins.frontend.lib.NodeInstaller.extractFile(NodeInstaller.java:324)
[ERROR]         at com.github.eirslett.maven.plugins.frontend.lib.NodeInstaller.installNodeDefault(NodeInstaller.java:143)
[ERROR]         ... 14 more
[ERROR] Caused by: java.nio.file.AccessDeniedException: Could not get write permissions for '/working/projects/redHat/Hyperfoil/Horreum/horreum-backend/../webapp/node/node/tmp/node-v18.1.0-linux-x64/bin'
[ERROR]         at com.github.eirslett.maven.plugins.frontend.lib.DefaultArchiveExtractor.prepDestination(ArchiveExtractor.java:51)
[ERROR]         at com.github.eirslett.maven.plugins.frontend.lib.DefaultArchiveExtractor.extract(ArchiveExtractor.java:111)
[ERROR]         ... 16 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

**Comment by johnaohara** [comment]
Ok, so removing `webapp/node` and `webapp/node_modules` resolves the issue

**Comment by jesperpedersen** [comment]
We need Quinoa to handle the download otherwise the OS native installation is used
