### ISSUE TITLE
 Change Detection Variable Deletion causes a 500 error

### ISSUE THREAD

**Issue by kdvalin** [Hyperfoil/Horreum#591]
**Describe the bug**
In a test that I'm editing on Red Hat's internal Horreum instance (https://horreum.corp.redhat.com/test/212), when deleting a variable in change detection, upon clicking "Save", a 500 error from the server occurs, and nothing is displayed to the user to indicate something went wrong.  No details are given in the 500 error that can be seen on the client browser.

**To Reproduce**
TBD

Simply making a new test, then adding a change detection variable, saving, then removing it does NOT reproduce this bug

**Comment by johnaohara** [comment]
@kdvalin this looks like a referential constraint that should have been solved by https://github.com/Hyperfoil/Horreum/pull/550 . 
@whitingjr Looks like we still might have an issue with fk constraints;

```
2023-07-11 17:19:35,445 2d64d8fced09 quarkus-run.jar[7] WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (executor-thread-7652) SQL Error: 0, SQLState: 23503
2023-07-11 17:19:35,446 2d64d8fced09 quarkus-run.jar[7] ERROR [org.hib.eng.jdb.spi.SqlExceptionHelper] (executor-thread-7652) ERROR: update or delete on table "variable" violates foreign key constraint "fk_datapoint_variable_id" on table "datapoint"
  Detail: Key is still referenced from table "datapoint".
2023-07-11 17:19:35,446 2d64d8fced09 quarkus-run.jar[7] INFO  [org.hib.eng.jdb.bat.int.AbstractBatchImpl] (executor-thread-7652) HHH000010: On release of batch it still contained JDBC statements
2023-07-11 17:19:35,447 2d64d8fced09 quarkus-run.jar[7] ERROR [io.hyp.too.hor.svc.AlertingServiceImpl] (executor-thread-7652) Failed to update variables: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1705)
        at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.delete(AbstractJpaOperations.java:405)
        at io.hyperfoil.tools.horreum.entity.alerting.DataPoint.delete(DataPoint.java)
        at io.hyperfoil.tools.horreum.svc.AlertingServiceImpl.lambda$updateVariables$38(AlertingServiceImpl.java:794)

```

**Comment by kdvalin** [comment]
For clarity:  This is not a blocker for me presently, but it is a bit annoying

**Comment by whitingjr** [comment]
@johnaohara yes it looks like the trigger called `before_variable_delete` in #550 was not deployed to the db. The function `before_variable_delete_func` did get in.

**Comment by jesperpedersen** [comment]
before_variable_delete is installed on variable

**Comment by jesperpedersen** [comment]
```
1713979 [2023-07-12 10:22:19.103 EDT] [horreum] [4433110] ERROR:  update or delete on table "variable" violates foreign key constraint "fk_datapoint_variable_id" on table "datapoint"
1713979 [2023-07-12 10:22:19.103 EDT] [horreum] [4433110] DETAIL:  Key is still referenced from table "datapoint".
1713979 [2023-07-12 10:22:19.103 EDT] [horreum] [4433110] STATEMENT:  delete from variable where id=$1
```

**Comment by whitingjr** [comment]
I cannot recreate this issue using Change Detection Variables on another Test. Deletion of the Variable works as intended. For me the BEFORE DELETE trigger removes any Datapoint and Change rows before the Variable itself is deleted. This opaque issue reminds me that RLS may be tripping us up here.

**Comment by kdvalin** [comment]
Any progress on this?  This problem is still present, and I would like to remove some variables from change detection in my test.

**Comment by whitingjr** [comment]
This issue is still WIP (Work In Progress)

**Comment by johnaohara** [comment]
@kdvalin is this still an issue? I have been trying to recreate this issue using the production data and I am not able to recreate

**Comment by johnaohara** [comment]
nvm I can recreate

**Comment by johnaohara** [comment]
The root cause of the issue is that we have datapoints (from change detection) that have a `dataset_id` that no longer exists.  RLS is unable to verify ownership of these datapoints, so the delete fails for datapoints, then variable.delete also fails

Checking the referential integrity of the schema, there is a FK constraint on the datapoints table: https://github.com/Hyperfoil/Horreum/blob/master/horreum-backend/src/main/resources/db/changeLog.xml#L2236

However, the column was subsequently changed, and it does not appear to enforce that constraint any longer: https://github.com/Hyperfoil/Horreum/blob/master/horreum-backend/src/main/resources/db/changeLog.xml#L2888


Deleting the orphaned datapoints resolves the issue, but we need to ;
- clean up all orphaned datapoints 
- fix the referential integrity between datapoints and datasets

**Comment by johnaohara** [comment]
There is approx 1.1k datapoints affected by this issue

**Comment by whitingjr** [comment]
@kdvalin this issue has been solved. You can now delete the problem Change Detection Variables on your test.

**Comment by kdvalin** [comment]
I can confirm that this problem has been fixed.  Thank you!
