### ISSUE TITLE
CI passes, but with SQL exceptions logged during verify phase

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#622]
CI is green, however there are SQL exceptions logged during the Integration tests;

```
Caused by: org.postgresql.util.PSQLException: ERROR: cannot extract elements from a scalar
  Where: SQL statement "WITH rs AS (
                    SELECT 0 AS type, NULL AS key, NEW.data->>'$schema' AS uri, 0 AS source
                    UNION SELECT 1 AS type, values.key, values.value->>'$schema' AS uri, 0 AS source FROM jsonb_each(NEW.data) as values WHERE jsonb_typeof(NEW.data) = 'object'
                    UNION SELECT 2 AS type, (row_number() OVER () - 1)::text AS key, value->>'$schema' as uri, 0 AS source FROM jsonb_array_elements(NEW.data) WHERE jsonb_typeof(NEW.data) = 'array'
                    UNION SELECT 2 AS type, (row_number() OVER () - 1)::text AS key, value->>'$schema' as uri, 1 AS source FROM jsonb_array_elements(NEW.metadata) WHERE NEW.metadata IS NOT NULL
                ) INSERT INTO run_schemas(runid, testid, source, type, key, uri, schemaid)
                    SELECT NEW.id, NEW.testid, rs.source, rs.type, rs.key, rs.uri, schema.id FROM rs
                    JOIN schema ON schema.uri = rs.uri"
PL/pgSQL function rs_after_run_update() line 3 at SQL statement
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152)
	at io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:88)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
	... 64 more
```

**Comment by johnaohara** [comment]
For example: https://github.com/Hyperfoil/Horreum/actions/runs/5868283174/job/15910749414?pr=620#step:7:3487

**Comment by stalep** [comment]
Can not see these exceptions any longer in master, @johnaohara?

**Comment by johnaohara** [comment]
No, I do not see these errors in the logs any longer
