### ISSUE TITLE
Web UI: adding a tag to existing test causes cascade error.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#63]
On the page to edit a Test I am seeing an error when adding a tag and clicking the Save button.

```
{
  "details": "javax.persistence.PersistenceException: org.hibernate.HibernateException: A collection with cascade=\"all-delete-orphan\" was no longer referenced by the owning entity instance: io.hyperfoil.tools.horreum.entity.json.Test.tokensError id 3b4afb00-f2ef-42cb-b332-bfc1e83d7572-1",
  "stack": ""
}
```
the server log has this stack trace
```
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1349)
	at org.hibernate.query.internal.NativeQueryImpl.beforeQuery(NativeQueryImpl.java:267)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1591)
	at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1641)
	at io.hyperfoil.tools.horreum.api.SqlService.lambda$withRoles$1(SqlService.java:173)
	at io.hyperfoil.tools.horreum.api.TestService.add(TestService.java:110)
	at io.hyperfoil.tools.horreum.api.TestService_Subclass.add$$superaccessor7(TestService_Subclass.zig:1433)
	at io.hyperfoil.tools.horreum.api.TestService_Subclass$$function$$7.apply(TestService_Subclass$$function$$7.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)

```

**Comment by rvansa** [comment]
Fixed.
