### ISSUE TITLE
Code Cache dsiabled in Dev mode

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#771]
I keep seeing the following warning in Dev mode console;

```
[236.828s][warning][codecache] CodeCache is full. Compiler has been disabled.
[236.828s][warning][codecache] Try increasing the code cache size using -XX:ReservedCodeCacheSize=
OpenJDK 64-Bit Server VM warning: CodeCache is full. Compiler has been disabled.
OpenJDK 64-Bit Server VM warning: Try increasing the code cache size using -XX:ReservedCodeCacheSize=
CodeCache: size=49152Kb used=49146Kb max_used=49146Kb free=5Kb
 bounds [0x00007f2541400000, 0x00007f2544400000, 0x00007f2544400000]
 total_blobs=27656 nmethods=26601 adapters=974
 compilation: disabled (not enough contiguous free space left)
              stopped_count=1, restarted_count=0
 full_count=0

```

It may be a local issue, but has started happening recently

**Comment by johnaohara** [comment]
```
$ java -version
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7)
OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode, sharing)
```

**Comment by dbutenhof** [comment]
I'm seeing failure of 5 different tests with `mvn quarkus:dev -pl 'horreum-backend'`, with classloader issues that may be related to this code cache problem:

```
2023-11-01 09:40:23,208 ERROR [io.qua.test] (Test runner thread) ==================== TEST REPORT #1 ====================
2023-11-01 09:40:23,208 ERROR [io.qua.test] (Test runner thread) Test RunServiceTest#testListAllRunsFromFiles() failed 
: org.opentest4j.AssertionFailedError: Could not find resource directory, aborting test
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:134)
--      at io.hyperfoil.tools.horreum.svc.BaseServiceTest.populateDataFromFiles(BaseServiceTest.java:841)
2023-11-01 09:40:23,209 ERROR [io.qua.test] (Test runner thread) Test SchemaServiceTest#testImportWithTransformers() failed 
: java.lang.NullPointerException: Cannot invoke "java.net.URL.getPath()" because the return value of "java.lang.ClassLoader.getResource(String)" is null
	at io.hyperfoil.tools.horreum.svc.SchemaServiceTest.testImportWithTransformers(SchemaServiceTest.java:199)
```

* RunServiceTest#testListAllRunsFromFiles()
* SchemaServiceTest#testImportWithTransformers()
* AlertingServiceTest#testFindLastDatapoints(TestInfo)
* TestServiceTest#testImportWithTransformers()
* TestServiceTest#testImportFromFile()

```
dbutenho 10:13 hslack:slack java --version
openjdk 17.0.8 2023-07-18
OpenJDK Runtime Environment (Red_Hat-17.0.8.0.7-1.fc38) (build 17.0.8+7)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.8.0.7-1.fc38) (build 17.0.8+7, mixed mode, sharing)

dbutenho 10:13 hslack:slack mvn --version
Apache Maven 3.8.6 (Red Hat 3.8.6-4)
Maven home: /usr/share/maven
Java version: 17.0.8, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-17-openjdk-17.0.8.0.7-1.fc38.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.5.8-200.fc38.x86_64", arch: "amd64", family: "unix"
```

**Comment by jesperpedersen** [comment]
@dbutenhof OS and Docker version ?

**Comment by jesperpedersen** [comment]
@dbutenhof Are you running this from a developer environment or from the CLI ?

**Comment by jesperpedersen** [comment]
Does it work with

```
mvn -Dquarkus.test.continuous-testing=disabled quarkus:dev -pl 'horreum-backend'
```

?

**Comment by johnaohara** [comment]
Another option, just to see if dev mode will startup is to disable the JIT: `mvn -Djava.compiler=NONE quarkus:dev -pl 'horreum-backend'`

**Comment by dbutenhof** [comment]
> Does it work with
> 
> ```
> mvn -Dquarkus.test.continuous-testing=disabled quarkus:dev -pl 'horreum-backend'
> ```

That actually fails fairly quickly with:

```
2023-11-01 11:34:39,692 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	... 15 more
Caused by: java.util.NoSuchElementException: SRCFG00014: The config property quarkus.oidc.auth-server-url is required but it could not be found in any config source
```

**Comment by jesperpedersen** [comment]
@dbutenhof Can you try and switch podman with docker ?

**Comment by dbutenhof** [comment]
> @dbutenhof Can you try and switch podman with docker ?

I guessed that might be coming, although I resisted the reconfiguration. (Not that it's a big deal to `dnf erase podman-docker ; dnf install docker` since I'm not using the docker emulation for anything else.)

```
dbutenho 12:02 hslack:slack docker --version
Docker version 24.0.5, build %{shortcommit_cli}
```

No difference at all in the behavior of the original `mvn quarkus:dev -pl 'horreum-backend'` command. The same 5 tests fail, the same way.

With `mvn -Dquarkus.test.continuous-testing=disabled quarkus:dev -pl 'horreum-backend'` ... it seems to be running really slowly. Or hung. No errors yet, but I walked away for a few minutes, and at 12:15 the last info log message was 12:04 (from the AMPQ event loop). I'm not sure it's making progress, but the dev environment doesn't show "paused" and it didn't complete, so I infer that it thinks it's still running something. 😆

In any case, I quit and tried John's suggestion of disabling the compiler with `mvn -Djava.compiler=NONE quarkus:dev -pl 'horreum-backend'`. This seems to get me to exactly the same point (fairly quickly) but shows "Tests paused" (with no clue why, but I remember that happening in my original runs, too), and with a `[r]`esume cue.

It ultimately fails with the same familiar 5 errors and, interestingly, shows the familiar "CodeCache is full. Compiler has been disabled." message despite presumably having disabled the compiler in the first place.

**Comment by johnaohara** [comment]
Thinking about it some more, the command args I suggested would have disabled jit for the maven process, not quarkus running in dev mode.

To test disabling JIT for quarkus in dev mode, execute: ` mvn quarkus:dev -pl 'horreum-backend' -Djvm.args="-Djava.compiler=NONE"`

**Comment by dbutenhof** [comment]
> mvn quarkus:dev -pl 'horreum-backend' -Djvm.args="-Djava.compiler=NONE"

Fails with the same `java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0` reflection exception I quoted earlier. Interestingly, this one also "pauses" with a `[r]esume` prompt, but resuming changes the prompt to `[r]erun` then apparently goes ahead and tries; but only shows `Running 1/78. Running: io.hyperfoil.tools.horreum.svc.ActionServiceTest#ActionServiceTest` and seems to hang there.
