### ISSUE TITLE
NullPointerException in UI after transformer re-transform

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#820]
After loading the example dataset, and clicking "Re-transform datasets" in the "transformers" view of 'Roadrunner test", navigate back to datasets and try to select a dataset.

Server-side error message: 

```
2023-10-26 07:43:33,230 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-8) HTTP Request to /api/dataset/2 failed, error id: 8d4cf331-9ef0-4891-84de-45528aa259b4-2: java.lang.NullPointerException: Cannot invoke "io.hyperfoil.tools.horreum.entity.data.DatasetDAO.getId()" because "ds" is null
	at io.hyperfoil.tools.horreum.mapper.DatasetMapper.from(DatasetMapper.java:14)
	at io.hyperfoil.tools.horreum.svc.DatasetServiceImpl.getDataset(DatasetServiceImpl.java:352)
	at io.hyperfoil.tools.horreum.svc.DatasetServiceImpl_Subclass.getDataset$$superforward(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.DatasetServiceImpl_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
	at io.hyperfoil.tools.horreum.server.TokenInterceptor.wrap(TokenInterceptor.java:49)
	at io.hyperfoil.tools.horreum.server.TokenInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.hyperfoil.tools.horreum.server.RolesInterceptor.intercept(RolesInterceptor.java:70)
	at io.hyperfoil.tools.horreum.server.RolesInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at io.hyperfoil.tools.horreum.svc.DatasetServiceImpl_Subclass.getDataset(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.DatasetServiceImpl_ClientProxy.getDataset(Unknown Source)
	at io.hyperfoil.tools.horreum.api.services.DatasetService$quarkusrestinvoker$getDataset_2b695bd874e8031735573fdf8a65f7cf4ef5964f.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by johnaohara** [comment]
Look like a race between what is available from the system ,and what datasets are cached in the UI
