### ISSUE TITLE
Evaluating experiment window not loading.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#883]
**Describe the bug**

The Evaluate Experiment window is not loading from the Run Datasets page.
This error is displayed in a popup window.

```
Warning alert:Cannot evaluate experiment

{
  "details": "Error id 62f8f246-b366-4ac8-9271-0a244826b242-3",
  "stack": ""
}
```
![experiment-error](https://github.com/Hyperfoil/Horreum/assets/708428/ddccdd45-59bf-4e37-b6b4-0129e4fe5f89)

On the server this exception is displayed.
```

2023-11-10 09:36:59,128 ERROR [io.hyp.too.hor.ser.ErrorReporter] (executor-thread-4859) Exception in handler for message bus channel DATAPOINT_PROCESSED, message io.hyperfoil.tools.horreum.api.alerting.DataPoint$DatasetProcessedEvent@77044904

: java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.asInt(int)" because the return value of "com.fasterxml.jackson.databind.JsonNode.get(String)" is null
	at io.hyperfoil.tools.horreum.experiment.RelativeDifferenceExperimentModel.compare(RelativeDifferenceExperimentModel.java:26)
	at io.hyperfoil.tools.horreum.svc.ExperimentServiceImpl.runExperiments(ExperimentServiceImpl.java:272)
	at io.hyperfoil.tools.horreum.svc.ExperimentServiceImpl.onDatapointsCreated(ExperimentServiceImpl.java:145)
	at io.hyperfoil.tools.horreum.svc.ExperimentServiceImpl_Subclass.onDatapointsCreated$$superforward(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.ExperimentServiceImpl_Subclass$$function$$5.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
	at io.hyperfoil.tools.horreum.server.RolesInterceptor.intercept(RolesInterceptor.java:70)
	at io.hyperfoil.tools.horreum.server.RolesInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.hyperfoil.tools.horreum.server.BaseTransactionRetryInterceptor.intercept(BaseTransactionRetryInterceptor.java:29)
	at io.hyperfoil.tools.horreum.server.BaseTransactionRetryInterceptor_RequiredTransactionRetryInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at io.hyperfoil.tools.horreum.svc.ExperimentServiceImpl_Subclass.onDatapointsCreated(Unknown Source)
	at io.hyperfoil.tools.horreum.bus.MessageBus.lambda$subscribe$3(MessageBus.java:157)
	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
	at io.hyperfoil.tools.horreum.svc.Util.lambda$wrapForBlockingExecution$3(Util.java:496)
	at io.hyperfoil.tools.horreum.bus.TaskQueue.executeOrAdd(TaskQueue.java:27)
	at io.hyperfoil.tools.horreum.bus.MessageBus.lambda$executeForTest$9(MessageBus.java:296)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:180)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
	at io.vertx.core.impl.ContextBase.lambda$internalExecuteBlocking$2(ContextBase.java:199)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**To Reproduce**

Unknown.

**Version**

0.9.6

**Comment by whitingjr** [comment]
Attempting to set the max datasets in the baseline with a value is not working. The sliding scale UI widget to set the value for the max datasets in baseline value is not working.
 This screenshot shows the sliding scale bar is above the 0 point on the scale. But the value remains 0. 
![unresponsive-ui-widget-max-datasets-in-baseline](https://github.com/Hyperfoil/Horreum/assets/708428/e0ba6cce-097a-4017-bb6b-5819dae229b4)
 Saving the updated experiment has no effect on the configuration stored for the experiment. The NullPointerException still occurs.

**Comment by whitingjr** [comment]
Inspecting the HTTP request to save the comparisons configuration shows the config object for each comparison does have a maxBaselineDatasets property with a 0 value.

**Comment by whitingjr** [comment]
The javascript console is reporting this error
```
Uncaught TypeError: can't assign to property "maxBaselineDatasets" on "{\"maxBaselineDatasets\":0,\"threshold\":0.1,\"greaterBetter\":true}": not an object
    onChange Experiments.tsx:358
    onChange ConditionComponent.tsx:22
    onChange LogSlider.tsx:48
    oe Slider.tsx:263
    onClick Slider.tsx:194
    React 11
Experiments.tsx:358:53

```
