### ISSUE TITLE
Upload to Horreum failed with aborted transaction

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#90]
An upload from the jenkins-horreum-plugin timed out and failed after approx 13mins.  The corresponding log in the application was :

```
2021-12-08 11:11:07,779 WARN  [com.arj.ats.arjuna] (Transaction Reaper) ARJUNA012117: TransactionReaper::check processing TX 0:ffff0a58007c:8649:61adcf7b:2359 in state  RUN
2021-12-08 11:11:07,782 WARN  [com.arj.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012095: Abort of action id 0:ffff0a58007c:8649:61adcf7b:2359 invoked while multiple threads active within it.
2021-12-08 11:11:07,784 WARN  [com.arj.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012381: Action id 0:ffff0a58007c:8649:61adcf7b:2359 completed with multiple threads - thread executor-thread-532 was in progress with java.base@11.0.5/java.net.SocketInputStream.socketRead0(Native Method)
java.base@11.0.5/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
java.base@11.0.5/java.net.SocketInputStream.read(SocketInputStream.java:168)
java.base@11.0.5/java.net.SocketInputStream.read(SocketInputStream.java:140)
org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:161)
org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:128)
org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:113)
org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:73)
org.postgresql.core.PGStream.receiveChar(PGStream.java:443)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2056)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130)
io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:88)
org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3381)
org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3908)
org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:107)
org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
org.hibernate.engine.spi.ActionQueue$$Lambda$919/0x0000000800b09c40.accept(Unknown Source)
java.base@11.0.5/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:344)
org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
org.hibernate.internal.SessionImpl$$Lambda$845/0x0000000800a16c40.accept(Unknown Source)
org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1391)
org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1378)
io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.flush(TransactionScopedSession.java:213)
io.quarkus.hibernate.orm.runtime.session.ForwardingSession.flush(ForwardingSession.java:93)
org.hibernate.Session_5b93bee577ae2f8d76647de04cfab36afbf52958_Synthetic_ClientProxy.flush(Session_5b93bee577ae2f8d76647de04cfab36afbf52958_Synthetic_ClientProxy.zig:2761)
io.hyperfoil.tools.horreum.svc.RunServiceImpl.addAuthenticated(RunServiceImpl.java:430)
io.hyperfoil.tools.horreum.svc.RunServiceImpl.addRunFromData(RunServiceImpl.java:366)
io.hyperfoil.tools.horreum.svc.RunServiceImpl_Subclass.addRunFromData$$superforward1(RunServiceImpl_Subclass.zig:1050)
io.hyperfoil.tools.horreum.svc.RunServiceImpl_Subclass$$function$$10.apply(RunServiceImpl_Subclass$$function$$10.zig:83)
io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
io.quarkus.security.runtime.interceptor.SecurityHandler.handle(SecurityHandler.java:24)
io.quarkus.security.runtime.interceptor.PermitAllInterceptor.intercept(PermitAllInterceptor.java:23)
io.quarkus.security.runtime.interceptor.PermitAllInterceptor_Bean.intercept(PermitAllInterceptor_Bean.zig:327)
io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:132)
io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:103)
io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:57)
io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:340)
io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
io.hyperfoil.tools.horreum.svc.RunServiceImpl_Subclass.addRunFromData(RunServiceImpl_Subclass.zig:2259)
io.hyperfoil.tools.horreum.svc.RunServiceImpl_ClientProxy.addRunFromData(RunServiceImpl_ClientProxy.zig:571)
jdk.internal.reflect.GeneratedMethodAccessor130.invoke(Unknown Source)
java.base@11.0.5/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base@11.0.5/java.lang.reflect.Method.invoke(Method.java:566)
org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
org.jboss.resteasy.core.ResourceMethodInvoker$$Lambda$880/0x0000000800ac7440.get(Unknown Source)
org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$877/0x0000000800ac0c40.run(Unknown Source)
org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$878/0x0000000800ac7c40.get(Unknown Source)
org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)
io.quarkus.resteasy.runtime.ResteasyFilter.doFilter(ResteasyFilter.java:35)
io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
io.hyperfoil.tools.horreum.server.GrafanaUserFilter.doFilter(GrafanaUserFilter.java:103)
javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:97)
io.hyperfoil.tools.horreum.server.GrafanaUserFilter_ClientProxy.doFilter(GrafanaUserFilter_ClientProxy.zig:284)
io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
io.hyperfoil.tools.horreum.server.UserTeamsFilter.doFilter(UserTeamsFilter.java:71)
javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:97)
io.hyperfoil.tools.horreum.server.UserTeamsFilter_ClientProxy.doFilter(UserTeamsFilter_ClientProxy.zig:284)
io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
io.hyperfoil.tools.horreum.server.RouteFilter.doFilter(RouteFilter.java:28)
io.hyperfoil.tools.horreum.server.RouteFilter_ClientProxy.doFilter(RouteFilter_ClientProxy.zig:284)
io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)
io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)
io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)
io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)
io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:247)
io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:56)
io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:111)
io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:108)
io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:584)
io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)
io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:152)
io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:119)
io.undertow.server.Connectors.executeRootHandler(Connectors.java:290)
io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)
io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$1.run(UndertowDeploymentRecorder.java:406)
java.base@11.0.5/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
java.base@11.0.5/java.util.concurrent.FutureTask.run(FutureTask.java:264)
io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
java.base@11.0.5/java.lang.Thread.run(Thread.java:834)

2021-12-08 11:11:07,784 WARN  [com.arj.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012108: CheckedAction::check - atomic action 0:ffff0a58007c:8649:61adcf7b:2359 aborting with 1 threads active!
2021-12-08 11:11:07,792 WARN  [io.agr.pool] (Transaction Reaper Worker 0) Datasource '<default>': JDBC resources leaked: 0 ResultSet(s) and 1 Statement(s)
2021-12-08 11:11:07,795 WARN  [com.arj.ats.jta] (Transaction Reaper Worker 0) ARJUNA016045: attempted rollback of < formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffff0a58007c:8649:61adcf7b:2359, node_name=quarkus, branch_uid=0:ffff0a58007c:8649:61adcf7b:235c, subordinatenodename=null, eis_name=0 > (io.agroal.narayana.LocalXAResource@79c6245f) failed with exception code XAException.XAER_RMERR: javax.transaction.xa.XAException: Error trying to transactionRollback local transaction: Enlisted connection used without active transaction
	at io.agroal.narayana.LocalXAResource.xaException(LocalXAResource.java:140)
	at io.agroal.narayana.LocalXAResource.xaException(LocalXAResource.java:134)
	at io.agroal.narayana.LocalXAResource.rollback(LocalXAResource.java:88)
	at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelAbort(XAResourceRecord.java:362)
	at com.arjuna.ats.arjuna.coordinator.BasicAction.doAbort(BasicAction.java:3037)
	at com.arjuna.ats.arjuna.coordinator.BasicAction.doAbort(BasicAction.java:3016)
	at com.arjuna.ats.arjuna.coordinator.BasicAction.Abort(BasicAction.java:1679)
	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.cancel(TwoPhaseCoordinator.java:124)
	at com.arjuna.ats.arjuna.AtomicAction.cancel(AtomicAction.java:215)
	at com.arjuna.ats.arjuna.coordinator.TransactionReaper.doWork(TransactionReaper.java:431)
	at com.arjuna.ats.internal.arjuna.coordinator.ReaperWorkerThread.run(ReaperWorkerThread.java:78)
Caused by: java.sql.SQLException: Enlisted connection used without active transaction
	at io.agroal.pool.ConnectionHandler.verifyEnlistment(ConnectionHandler.java:362)
	at io.agroal.pool.ConnectionHandler.transactionRollback(ConnectionHandler.java:337)
	at io.agroal.narayana.LocalXAResource.rollback(LocalXAResource.java:85)
	... 8 more

2021-12-08 11:11:08,280 WARN  [com.arj.ats.arjuna] (Transaction Reaper) ARJUNA012117: TransactionReaper::check processing TX 0:ffff0a58007c:8649:61adcf7b:2359 in state  CANCEL
2021-12-08 11:11:08,282 WARN  [com.arj.ats.arjuna] (Transaction Reaper) ARJUNA012378: ReaperElement appears to be wedged: org.postgresql.core.QueryExecutorBase.getTransactionState(QueryExecutorBase.java:274)
org.postgresql.jdbc.PgConnection.commit(PgConnection.java:870)
org.postgresql.jdbc.PgConnection.setAutoCommit(PgConnection.java:813)
io.agroal.pool.ConnectionHandler.resetConnection(ConnectionHandler.java:138)
io.agroal.pool.ConnectionPool.returnConnectionHandler(ConnectionPool.java:399)
io.agroal.pool.ConnectionHandler.transactionEnd(ConnectionHandler.java:349)
io.agroal.narayana.NarayanaTransactionIntegration$InterposedSynchronization.afterCompletion(NarayanaTransactionIntegration.java:188)
com.arjuna.ats.internal.jta.resources.arjunacore.SynchronizationImple.afterCompletion(SynchronizationImple.java:96)
com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.afterCompletion(TwoPhaseCoordinator.java:545)
com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.afterCompletion(TwoPhaseCoordinator.java:472)
com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.cancel(TwoPhaseCoordinator.java:127)
com.arjuna.ats.arjuna.AtomicAction.cancel(AtomicAction.java:215)
com.arjuna.ats.arjuna.coordinator.TransactionReaper.doWork(TransactionReaper.java:431)
com.arjuna.ats.internal.arjuna.coordinator.ReaperWorkerThread.run(ReaperWorkerThread.java:78)

2021-12-08 11:11:08,782 WARN  [com.arj.ats.arjuna] (Transaction Reaper) ARJUNA012117: TransactionReaper::check processing TX 0:ffff0a58007c:8649:61adcf7b:2359 in state  CANCEL_INTERRUPTED
2021-12-08 11:11:08,783 WARN  [com.arj.ats.arjuna] (Transaction Reaper) ARJUNA012120: TransactionReaper::check worker Thread[Transaction Reaper Worker 0,5,main] not responding to interrupt when cancelling TX 0:ffff0a58007c:8649:61adcf7b:2359 -- worker marked as zombie and TX scheduled for mark-as-rollback
2021-12-08 11:11:08,783 WARN  [com.arj.ats.arjuna] (Transaction Reaper) ARJUNA012110: TransactionReaper::check successfuly marked TX 0:ffff0a58007c:8649:61adcf7b:2359 as rollback only
```

**Comment by johnaohara** [comment]
Client side stack trace

```
org.apache.http.NoHttpResponseException: horreum.usersys.redhat.com:8443 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:323)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to mwperf-baremetal
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at jenkins.plugins.horreum.HorreumBaseStep$Execution.run(HorreumBaseStep.java:56)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
		at hudson.security.ACL.impersonate2(ACL.java:449)
		at hudson.security.ACL.impersonate(ACL.java:461)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Caused: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:328)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:443)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:149)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy38.addRunFromData(Unknown Source)
	at jenkins.plugins.horreum.upload.HorreumUploadExecutionContext.invoke(HorreumUploadExecutionContext.java:66)
	at jenkins.plugins.horreum.upload.HorreumUploadExecutionContext.invoke(HorreumUploadExecutionContext.java:23)
	at jenkins.plugins.horreum.BaseExecutionContext.call(BaseExecutionContext.java:56)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:375)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by rvansa** [comment]
I will reject this as it is probably not a problem in this project but in pgagroal.

**Comment by jesperpedersen** [comment]
Cc: @barreiro

**Comment by jesperpedersen** [comment]
@barreiro 

```
2021-12-08 11:11:08,282 WARN  [com.arj.ats.arjuna] (Transaction Reaper) ARJUNA012378: ReaperElement appears to be wedged: org.postgresql.core.QueryExecutorBase.getTransactionState(QueryExecutorBase.java:274)
org.postgresql.jdbc.PgConnection.commit(PgConnection.java:870)
org.postgresql.jdbc.PgConnection.setAutoCommit(PgConnection.java:813)
io.agroal.pool.ConnectionHandler.resetConnection(ConnectionHandler.java:138)
io.agroal.pool.ConnectionPool.returnConnectionHandler(ConnectionPool.java:399)
io.agroal.pool.ConnectionHandler.transactionEnd(ConnectionHandler.java:349)
io.agroal.narayana.NarayanaTransactionIntegration$InterposedSynchronization.afterCompletion(NarayanaTransactionIntegration.java:188)
com.arjuna.ats.internal.jta.resources.arjunacore.SynchronizationImple.afterCompletion(SynchronizationImple.java:96)
com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.afterCompletion(TwoPhaseCoordinator.java:545)
com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.afterCompletion(TwoPhaseCoordinator.java:472)
```

I would pass `status` to `transactionEnd` such that this stack trace calls rollback instead of commit...
