### ISSUE TITLE
Python client generation errors openapi generator

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#930]
The python openapi generator is failing to generate code with the following error;

```
$ openapi-python-client  generate --path  ./horreum-api/target/generated/openapi.yaml 
Generating horreum-rest-api-client
Error(s) encountered while generating, client was not created

WARNING parsing GET /api/experiment/run within experiment.

Cannot parse response for status code 200 (Could not find reference in parsed models or enums), response will be ommitted from generated client

Reference(ref='#/components/schemas/ExperimentResult')

WARNING parsing GET /api/experiment/{testId}/profiles within experiment.

Cannot parse response for status code 200 (Could not find reference in parsed models or enums), response will be ommitted from generated client

Reference(ref='#/components/schemas/ExperimentProfile')

WARNING parsing POST /api/experiment/{testId}/profiles within experiment. Endpoint will not be generated.

Could not find reference in parsed models or enums

Reference(ref='#/components/schemas/ExperimentProfile')


Unable to process schema /components/schemas/ComparisonResult:

Cannot take allOf a non-object

Failure to process schema has resulted in the removal of:
/components/schemas/ComparisonResult
/components/schemas/ExperimentResult



Unable to process schema /components/schemas/ExperimentComparison:

type array must have items defined

Failure to process schema has resulted in the removal of:
/components/schemas/ExperimentComparison
/components/schemas/ExperimentProfile

Schema(title=None, multipleOf=None, maximum=None, exclusiveMaximum=None, minimum=None, exclusiveMinimum=None, maxLength=None, minLength=None, pattern=None, maxItems=None, minItems=None, uniqueItems=None, maxProperties=None, minProperties=None, required=None, enum=None, type=<DataType.ARRAY: 'array'>, allOf=[], oneOf=[], anyOf=[], schema_not=None, items=None, properties=None, additionalProperties=None, description='Model JSON configuration', schema_format=None, default=None, nullable=False, discriminator=None, readOnly=None, writeOnly=None, xml=None, externalDocs=None, example=None, deprecated=None)


Unable to process schema /components/schemas/TableReportData:

type array must have items defined

Failure to process schema has resulted in the removal of:
/components/schemas/TableReportData

Schema(title=None, multipleOf=None, maximum=None, exclusiveMaximum=None, minimum=None, exclusiveMinimum=None, maxLength=None, minLength=None, pattern=None, maxItems=None, minItems=None, uniqueItems=None, maxProperties=None, minProperties=None, required=None, enum=None, type=<DataType.ARRAY: 'array'>, allOf=[], oneOf=[], anyOf=[], schema_not=None, items=None, properties=None, additionalProperties=None, description=None, schema_format=None, default=None, nullable=False, discriminator=None, readOnly=None, writeOnly=None, xml=None, externalDocs=None, example=None, deprecated=None)

autoflake failed

Traceback (most recent call last):
  File "/home/johara/.local/bin/autoflake", line 5, in <module>
    from autoflake import main
  File "/home/johara/.local/lib/python3.11/site-packages/autoflake.py", line 105, in <module>
    frozenset(standard_package_names()) - IMPORTS_WITH_SIDE_EFFECTS | BINARY_IMPORTS
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johara/.local/lib/python3.11/site-packages/autoflake.py", line 75, in standard_package_names
    for name in standard_paths():
  File "/home/johara/.local/lib/python3.11/site-packages/autoflake.py", line 65, in standard_paths
    yield from os.listdir(path)
               ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib64/python3.11'

```

**Comment by johnaohara** [comment]
Fxied by: https://github.com/Hyperfoil/Horreum/pull/1067
