### ISSUE TITLE
Find Usages button causes ClassCast Exception

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#944]
Clicking on the "Find Usages" button in the Schema labels view causes Classcast Exception

![image](https://github.com/Hyperfoil/Horreum/assets/959822/8f955f2f-b589-4654-91eb-ff6b9df6bd78)

```
2023-11-24 13:00:02,766 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-13) HTTP Request to /api/schema/findUsages?label=buildType failed, error id: 6baa57ad-6b0d-48a4-afc2-0b21ad26012d-2: java.lang.ClassCastException: class java.lang.String cannot be cast to class com.fasterxml.jackson.databind.node.ArrayNode (java.lang.String is in module java.base of loader 'bootstrap'; com.fasterxml.jackson.databind.node.ArrayNode is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @3427b02d)
	at io.hyperfoil.tools.horreum.svc.SchemaServiceImpl.findUsages(SchemaServiceImpl.java:546)
	at io.hyperfoil.tools.horreum.svc.SchemaServiceImpl_Subclass.findUsages$$superforward(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.SchemaServiceImpl_Subclass$$function$$11.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
	at io.hyperfoil.tools.horreum.server.RolesInterceptor.intercept(RolesInterceptor.java:70)
	at io.hyperfoil.tools.horreum.server.RolesInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
	at io.quarkus.security.runtime.interceptor.SecurityHandler.handle(SecurityHandler.java:47)
	at io.quarkus.security.runtime.interceptor.PermitAllInterceptor.intercept(PermitAllInterceptor.java:23)
	at io.quarkus.security.runtime.interceptor.PermitAllInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor.intercept(StandardSecurityCheckInterceptor.java:44)
	at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor_PermitAllInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at io.hyperfoil.tools.horreum.svc.SchemaServiceImpl_Subclass.findUsages(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.SchemaServiceImpl_ClientProxy.findUsages(Unknown Source)
	at io.hyperfoil.tools.horreum.api.services.SchemaService$quarkusrestinvoker$findUsages_f3c1f0cf3c110e278a9826b7ad07e954a6e838f5.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by stalep** [comment]
Is this related to #883 as well?

**Comment by johnaohara** [comment]
I have not looked into it, but it is a similar class of issue, similar to: https://github.com/Hyperfoil/Horreum/issues/956

Although #956 is caused by a bug in the UI serializing the json as a String, and now the DB contains a `TextNode`, instead of an `ObjectNode`.  They are all the same class of errors where storing JsonNode in the database can store incompatible JSON types

**Comment by johnaohara** [comment]
This is caused by the query from DB now returning `String`, instead of a `JsonNodeBinaryType` for some fields: https://github.com/Hyperfoil/Horreum/pull/626/files#diff-102ceb75ecfbaf74b880bdbb4fbd034bcb176472b8c17f2dbcdbb281c5237c3aR485-R488

and then typecasting the result to (ArrayNode), which fails
