### ISSUE TITLE
NullPointerException opening evaluate experiments.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#951]
**Describe the bug**

2023-11-27 06:07:32,185 ERROR [io.hyp.too.hor.svc.AlertingServiceImpl] (executor-thread-2613) Recalculation failed: java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.asInt(int)" because the return value of "com.fasterxml.jackson.databind.JsonNode.get(String)" is null
	at io.hyperfoil.tools.horreum.experiment.RelativeDifferenceExperimentModel.compare(RelativeDifferenceExperimentModel.java:26)
	at io.hyperfoil.tools.horreum.svc.ExperimentServiceImpl.runExperiments(ExperimentServiceImpl.java:264)
	at io.hyperfoil.tools.horreum.svc.ExperimentServiceImpl.onDatapointsCreated(ExperimentServiceImpl.java:141)
	at io.hyperfoil.tools.horreum.svc.ExperimentServiceImpl_Subclass.onDatapointsCreated$$superforward(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.ExperimentServiceImpl_Subclass$$function$$5.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
	at io.hyperfoil.tools.horreum.server.RolesInterceptor.intercept(RolesInterceptor.java:70)
	at io.hyperfoil.tools.horreum.server.RolesInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInCallerTx(TransactionalInterceptorBase.java:335)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:40)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at io.hyperfoil.tools.horreum.svc.ExperimentServiceImpl_Subclass.onDatapointsCreated(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.ExperimentServiceImpl_ClientProxy.onDatapointsCreated(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.ServiceMediator.dataPointsProcessed(ServiceMediator.java:163)
	at io.hyperfoil.tools.horreum.svc.ServiceMediator_ClientProxy.dataPointsProcessed(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceImpl.emitDatapoints(AlertingServiceImpl.java:493)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceImpl.recalculateDatapointsForDataset(AlertingServiceImpl.java:280)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceImpl.recalculateForDataset(AlertingServiceImpl.java:990)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceImpl_Subclass.recalculateForDataset$$superforward(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceImpl_Subclass$$function$$23.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
	at io.hyperfoil.tools.horreum.server.RolesInterceptor.intercept(RolesInterceptor.java:70)
	at io.hyperfoil.tools.horreum.server.RolesInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequiresNew.doIntercept(TransactionalInterceptorRequiresNew.java:41)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequiresNew.intercept(TransactionalInterceptorRequiresNew.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequiresNew_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceImpl_Subclass.recalculateForDataset(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceImpl.startRecalculation(AlertingServiceImpl.java:952)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceImpl.lambda$recalculateDatapoints$51(AlertingServiceImpl.java:925)
	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
	at io.hyperfoil.tools.horreum.svc.Util.lambda$wrapForBlockingExecution$3(Util.java:482)
	at io.hyperfoil.tools.horreum.bus.TaskQueue.executeOrAdd(TaskQueue.java:27)
	at io.hyperfoil.tools.horreum.bus.MessageBus.lambda$executeForTest$4(MessageBus.java:95)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:180)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
	at io.vertx.core.impl.ContextBase.lambda$internalExecuteBlocking$2(ContextBase.java:199)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

**To Reproduce**

Click Evaluate Experiments button

**Version**

0.10.4

**Java**

```
17
```

**Comment by whitingjr** [comment]
@johnaohara I had been verbally told it had been fixed by @stalep back in November.

**Comment by johnaohara** [comment]
I may have seen this issue again because our prod version erroneously rolled back to 0.10.4.  If it is fixed, we need to link the fix to this issue, so we have a trail of fixes and issues
