### ISSUE TITLE
can not restart dev mode with backup database more than once

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Horreum#972]
The postgres container changes file permissions for the database directory of a backup database from prod.

The dev mode init scripts check the file permissions, which no longer belong to the system user and fails to start;

```
...
Caused by: java.lang.RuntimeException: Directory /working/databases/horreum-db/archive-primary-20231122075209/primary-20231122075209 does not have sufficient permissions to operate!
	at io.hyperfoil.tools.horreum.infra.common.resources.PostgresResource.checkIfDirectoryIsEmtpy(PostgresResource.java:94)
	at io.hyperfoil.tools.horreum.infra.common.resources.PostgresResource.init(PostgresResource.java:54)
	at io.hyperfoil.tools.horreum.infra.common.HorreumResources.startContainers(HorreumResources.java:145)
	at io.hyperfoil.tools.horreum.dev.services.deployment.HorreumDevServicesProcessor.startHorreumContainers(HorreumDevServicesProcessor.java:129)
	... 11 more

```

**Comment by johnaohara** [comment]
@whitingjr what was the error that this PR fixed: https://github.com/Hyperfoil/Horreum/pull/958 ?
